# SwiftLint Configuration for Assassin Game Design System

# Paths to include/exclude
included:
  - src/
  - tests/

excluded:
  - src/generated/
  - .build/
  - Packages/
  - docs/

# Rules to enable
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Rules to disable
disabled_rules:
  - todo
  - line_length # We'll set a custom length

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

file_length:
  warning: 500
  error: 1000

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 10

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50

# File header template
file_header:
  required_pattern: |
                    \/\/
                    \/\/ .*\.swift
                    \/\/ Assassin Game Design System
                    \/\/
                    \/\/ Created by .* on \d{1,2}\/\d{1,2}\/\d{4}\.
                    \/\/

# Custom rules for design system
custom_rules:
  design_tokens_usage:
    name: "Design Tokens Usage"
    regex: '(Color\(red:|Color\(#|\.padding\(\d+\)|\.font\(\.system\(size:)'
    message: "Use design tokens instead of hardcoded values"
    severity: warning
  
  component_naming:
    name: "Component Naming Convention"
    regex: '^(struct|class) [A-Z][a-zA-Z0-9]*(?:View|Button|Card|Field|Alert|Toast|Header|Footer|Navigation|Tab|Modal|Sheet)(?:: View)?'
    match_kinds:
      - typeidentifier
    message: "Components should follow naming convention: ComponentTypeView"
    severity: warning
  
  accessibility_labels:
    name: "Accessibility Labels"
    regex: '\.accessibilityLabel\(|\.accessibilityHint\(|\.accessibilityValue\('
    message: "Consider adding accessibility labels for better VoiceOver support"
    severity: warning
  
  preview_provider:
    name: "Preview Provider Required"
    regex: 'struct.*: View'
    message: "Add #Preview for SwiftUI views"
    severity: warning

# Reporter configuration
reporter: "github-actions-logging"

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration 