name: 🐛 Bug Report
description: Report a bug or issue with the design system
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug are you reporting?
      options:
        - Component Rendering Issue
        - Design Token Inconsistency
        - Figma Sync Problem
        - Documentation Error
        - Build/Compilation Error
        - Performance Issue
        - Accessibility Issue
        - Visual Regression
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - 🔥 Critical - Blocks development/production
        - 🚨 High - Major functionality broken
        - 📋 Medium - Minor functionality affected
        - 💡 Low - Cosmetic or edge case
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: "The component/feature does not work as expected..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: "I expected..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: "Instead, what happened was..."
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this bug?
      options:
        - TacticalButton
        - MissionCard
        - TargetCard
        - TacticalTextField
        - TacticalAlert
        - TacticalToast
        - Navigation Components
        - Design Tokens
        - Multiple Components
        - Unknown/Other
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - iOS Version: [e.g. 17.0]
        - Xcode Version: [e.g. 15.0]
        - Device: [e.g. iPhone 15 Pro]
        - Design System Version: [e.g. 1.2.0]
        - Simulator/Physical Device: [e.g. Simulator]
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Code Sample
      description: Minimal code sample that reproduces the issue
      render: swift
      placeholder: |
        ```swift
        // Your code here
        ```

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: Add screenshots or videos to help explain the problem
      placeholder: "Drag and drop images/videos here or paste URLs..."

  - type: textarea
    id: figma-comparison
    attributes:
      label: Figma vs Implementation
      description: If this is a visual issue, provide Figma design link and describe the difference
      placeholder: "Figma design: [link] - The implementation differs in..."

  - type: textarea
    id: console-logs
    attributes:
      label: Console Logs/Error Messages
      description: Any relevant console output or error messages
      render: shell
      placeholder: "Paste any error messages or console output here..."

  - type: checkboxes
    id: testing
    attributes:
      label: Testing Done
      description: What testing have you done?
      options:
        - label: Tested on multiple devices/simulators
        - label: Tested with different iOS versions
        - label: Tested with accessibility features enabled
        - label: Checked visual regression tests
        - label: Verified against Figma designs

  - type: textarea
    id: workaround
    attributes:
      label: Workaround
      description: Is there a temporary workaround for this issue?
      placeholder: "Currently using this workaround..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "This issue started happening after..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided clear steps to reproduce
          required: true
        - label: I have included relevant environment information
          required: true 