name: 🚀 Feature Request
description: Suggest a new feature or enhancement for the design system
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a feature! Please fill out the sections below to help us understand your request.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature are you requesting?
      options:
        - New Component
        - Design Token Enhancement
        - Figma Integration Improvement
        - Documentation Enhancement
        - Developer Experience
        - Accessibility Feature
        - Performance Optimization
        - Testing Enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How important is this feature?
      options:
        - 🔥 Critical - Blocking development
        - 🚨 High - Important for upcoming release
        - 📋 Medium - Nice to have soon
        - 💡 Low - Future consideration
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: "As a [role], I need [functionality] so that [benefit]..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution in detail
      placeholder: "I would like to see..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative approaches?
      placeholder: "Alternative approaches could include..."

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What would need to be true for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: dropdown
    id: component-category
    attributes:
      label: Component Category (if applicable)
      description: Which component category does this relate to?
      options:
        - Buttons
        - Cards
        - Forms
        - Navigation
        - Notifications
        - Maps
        - Design Tokens
        - Documentation
        - Tooling
        - N/A
    validations:
      required: false

  - type: checkboxes
    id: impact-areas
    attributes:
      label: Impact Areas
      description: Which areas will this feature impact?
      options:
        - label: Figma Design Files
        - label: SwiftUI Components
        - label: Design Tokens
        - label: Documentation
        - label: Testing
        - label: CI/CD Pipeline
        - label: Developer Experience
        - label: Accessibility
        - label: Performance

  - type: textarea
    id: figma-reference
    attributes:
      label: Figma Reference
      description: Link to relevant Figma designs or prototypes
      placeholder: "https://figma.com/file/..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
      placeholder: "Any additional information that would help us understand this request..."

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have provided clear acceptance criteria
          required: true
        - label: I have considered the impact on existing components
          required: true 